build:
  environment:
    php: 7.4

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests-and-coverage:
      tests:
        override:
          - command: 'php ./vendor/bin/phpunit --coverage-clover=clover.xml'
            coverage:
              file: clover.xml
              format: clover

filter:
  paths:
    - src/

  excluded_paths:
    - tests/
    - bin/
