language: php

jobs:
  include:
    - stage: "PHP7.4 - highest"
      php: 7.4
      script:
        - composer update -n --prefer-dist --no-suggest
        - composer dump-autoload
        - composer ci:tests
        - composer ci:php:psalm
